# Generated by Django 5.1.4 on 2025-01-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_game_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('title_ru', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('rank', models.IntegerField(blank=True, default=None, null=True)),
                ('voters_count', models.IntegerField(default=0)),
                ('bgg_rating', models.FloatField(default=0.0)),
                ('avg_rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
