# Generated by Django 5.1.4 on 2025-01-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='notes.group'),
            preserve_default=False,
        ),
    ]
