# Generated by Django 2.1.1 on 2018-08-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
